### ISSUE TITLE
[REVIEW] Lavavu examples not showing on binder

### ISSUE THREAD

**Issue by santisoler** [underworldcode/stripy#25]
Part of https://github.com/openjournals/joss-reviews/issues/1410

The interactive plotting of spherical triangulations using `lavavu` is not working as expected on binder.
I'm getting the following output cell:
![lavavu-binder](https://user-images.githubusercontent.com/11541317/57232469-07cb2280-6ff3-11e9-8618-6f552280cd44.png)

Don't know if it's something wrong with binder itself, or if `lavavu` is intended to work under Jupyter Notebooks. Do the notebooks work well locally on your systems?

**Comment by lmoresi** [comment]
lavavu should work in the binder but there is a continual battle between jupyter hub security and the various reverse-proxy strategies we have to follow to keep the lavavu service visible. 

@brmather - the known working solution is to use lavavu<1.3 (i.e. the final 1.2.x release) and make sure that binder is pointing to traditional notebook rather than jupyterlab. This is probably something that was not checked when I updated the docker images to fix the issues with the bash helpers. 

[[@brmather, I'm assigning this to you as I cannot tackle anything this week. Re-assign to me if you need to]]

**Comment by lmoresi** [comment]
I just checked with the binder / dockerfile with lavavu that I am using for a class. The current build does work with binder (which has changed its interface in the last few days) even when using the new default jupyter-lab.

So, that is commit **afa8cd24e6dae7ffbacf9735db8e1affd85fd3df** which we should probably specify explicitly in the dockerfile

**Comment by brmather** [comment]
OK this has been fixed with 693deb22fe203912ac017dbdb6917313c9c8f53e and should *stay* fixed since we have frozen the version of lavavu.

**Comment by lmoresi** [comment]
Not necessarily - there are some changes with binder that require particular versions of jupyterhub (I think) and this means we might have to update the dockerfile and the various lavavu tricks to integrate with it.

Fingers crossed it continues to work for a decent amount of time.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 8 May 2019, 2:31 PM +1000, Ben Mather <notifications@github.com>, wrote:

OK this has been fixed with 693deb2<https://github.com/underworldcode/stripy/commit/693deb22fe203912ac017dbdb6917313c9c8f53e> and should stay fixed since we have frozen the version of lavavu.
