### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by rmmilewi** [underworldcode/stripy#43]
Hello!

My name is Reed, and I'm a software engineering researcher at Sandia National Laboratories in the US. I've created an issue on your repo just to ask a quick question. If you don't have time or don't care to respond, feel free to ignore me and/or delete this issue.

Where I work, we have a very diverse ecosystem of cutting-edge research codes spanning every discipline you could imagine. I'm part of our software engineering research department, and it's our job to keep that ecosystem robust and healthy. Part of that means helping scientists to adopt good software practices. Right now, my mind has been on software versioning/release schemes (e.g. semantic versioning). 

In order to build a case for/against getting my people on-board with the practice, I figured I should ask people who already use versioning to release their software to see what they think. So I gathered up a list of scientific software repositories on GitHub, then I selected those that tracked versioned releases, that were reasonably active, etc.  Finally, I picked a handful of those repos and decided to reach out to them. You were on that list.

Anyway, here's the question:

> What do you believe are the benefits (or drawbacks) of having versioned releases of your software (i.e. 1.0.0, 1.1.0, 2.0.0...)? When should someone start thinking about versioning/releasing their code?

Just a sentence or two, that's all I need. For context, imagine the preceding sentence is this: "_But don't just take my word for it, just listen to what these accomplished researchers has to say!_".

Thank you so much!

Reed Milewicz
rmilewi@sandia.gov

**Comment by lmoresi** [comment]
There are many reasons to be organised about versioning and, at some stage, any software project has to adopt some form of version tagging. There are, however, some compelling reasons to start early:

1. It encourages some introspection / reflection - making regular small releases keeps the code well organised and encourages the developer to feel a little bit uncomfortable when things get too disorganised. 
2. The X.Y.Z form of release is helpful because it comes with a set of implied instructions: Important changes to the API are supposed to require an increment of X etc etc. This is really good discipline: see https://semver.org.
3. Version control and semantic tagging go hand in hand and work well together.
4. In python, pypi.org requires unique tags for each upload and that is very much easier if there is a clear pattern for the tags to increment in a meaningful way. With pip you need to be able to say `pip install "stripy>=1.0.0"` and for that to be resolvable in a logical manner. Same for other package managers.
5. Code-archives such as zenodo require unique release tags and it makes sense to have a natural increment in the tagging.

There are some disadvantages:

1. It is not always obvious that, say, v0.9 is earlier than v.0.10 
2. Sometimes it can be helpful to have the tags represent time (for example, when I work on course notes, I often use the year as the major version number as there is not a backwards-compatibility story with those kinds of materials).
3. There is not a mapping between the version and an individual commit when you are developing code. For this reason many people try to include a commit tag in the version number for between-release code that might be installed from a repo.

Hope that helps.

**Comment by rmmilewi** [comment]
You're amazing! Far above and beyond my expectations! I appreciate you taking the time to reply, I'll definitely be sharing your perspectives with the research teams in my care. Thank you again! :-D
