### ISSUE TITLE
ImportError: DLL load failed ...

### ISSUE THREAD

**Issue by wordsworthgroup** [underworldcode/stripy#90]
I just installed Visual Studio Build Tools on my Windows machine, then successfully installed `stripy` using `pip`. When importing though, I get
```
In [1]: from stripy import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1fdeae0028d1> in <module>
----> 1 from stripy import *

c:\users\markm\appdata\local\programs\python\python39\lib\site-packages\stripy\__init__.py in <module>
     32
     33
---> 34 from .spherical import sTriangulation
     35 from .cartesian import Triangulation
     36 from . import spherical_meshes

c:\users\markm\appdata\local\programs\python\python39\lib\site-packages\stripy\spherical.py in <module>
     19 #!/usr/bin/python
     20 # -*- coding: utf-8 -*-
---> 21 from . import _stripack
     22 from . import _ssrfpack
     23 import numpy as np

ImportError: DLL load failed while importing _stripack: The specified module could not be found.
```

Easy way to fix this? Am I missing installation steps?

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1616625689/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/fa3d0b59cb806ead8d122533eef96d03/a5575a5fb3fb7963c370a4a38ac2eeaf/newton.gif]

We find it quite difficult to support the pip install because there is a need to have compilers etc to manage the Fortran sub layer even though it is already compiled.

If you have conda installed, you can access stripy from the geo-down-under channel and that usually does a much better job with the FORTRAN library requirement.



Prof Louis Moresi
***@***.******@***.***>
(m) +61 4 0333 1413<tel:+61403331413>
(us) +1 505 349 4425<tel:+15053494425>
www.moresi.info<https://tr.cloudmagic.com/h/v6/link-track/1.0/1616625706868656-9b5a81a5-649b-145e-79ef-829ac75e22c5/1616625689/e0463a85314d353cd65b915287a67da9/fa3d0b59cb806ead8d122533eef96d03/a5575a5fb3fb7963c370a4a38ac2eeaf?redirect_uri=http://www.moresi.info/>
geo-down-under.geoscience.education<https://tr.cloudmagic.com/h/v6/link-track/1.0/1616625706868674-d15e7345-c5d3-9d08-89b6-84f7e848848e/1616625689/e0463a85314d353cd65b915287a67da9/fa3d0b59cb806ead8d122533eef96d03/a5575a5fb3fb7963c370a4a38ac2eeaf?redirect_uri=https://geo-down-under.geoscience.education/>
@LouisMoresi<https://tr.cloudmagic.com/h/v6/link-track/1.0/1616625706868710-330c0f3b-9551-afc0-9080-32f8505ccd60/1616625689/e0463a85314d353cd65b915287a67da9/fa3d0b59cb806ead8d122533eef96d03/a5575a5fb3fb7963c370a4a38ac2eeaf?redirect_uri=https://twitter.com/LouisMoresi>

On Thu, Mar 25, 2021 at 2:54, Wordsworth Group ***@***.******@***.***>> wrote:

I just installed Visual Studio Build Tools on my Windows machine, then successfully installed stripy using pip. When importing though, I get

In [1]: from stripy import *
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1fdeae0028d1> in <module>
----> 1 from stripy import *

c:\users\markm\appdata\local\programs\python\python39\lib\site-packages\stripy\__init__.py in <module>
     32
     33
---> 34 from .spherical import sTriangulation
     35 from .cartesian import Triangulation
     36 from . import spherical_meshes

c:\users\markm\appdata\local\programs\python\python39\lib\site-packages\stripy\spherical.py<https://tr.cloudmagic.com/h/v6/link-track/1.0/1616625706868719-4e5448bc-b08d-152e-abf1-dbd5ec2727a3/1616625689/e0463a85314d353cd65b915287a67da9/fa3d0b59cb806ead8d122533eef96d03/a5575a5fb3fb7963c370a4a38ac2eeaf?redirect_uri=http://spherical.py> in <module>
     19 #!/usr/bin/python
     20 # -*- coding: utf-8 -*-
---> 21 from . import _stripack
     22 from . import _ssrfpack
     23 import numpy as np

ImportError: DLL load failed while importing _stripack: The specified module could not be found.


Easy way to fix this? Am I missing installation steps?

**Comment by wordsworthgroup** [comment]
Ok I can give it a try through conda. I checked that I have the `gfortran` compiler in my path. Who knows what happened. Thanks for the advice!

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1616641686/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/ea0fb6f11ed4721134a44abffb246245/f3579baed78d542c81fd034194633e7d/newton.gif]
It is quite mysterious and pip does not really keep track of the version of the fortran libraries that are used.

Conda is better like that if you can sustain the overhead in using it. Let us know. We don’t have many windows testers so we may have some more work to do.

Louis

On Thu, Mar 25, 2021 at 12:26 PM, Wordsworth Group ***@***.***> wrote:

Ok I can give it a try through conda. I checked that I have the gfortran compiler in my path. Who knows what happened. Thanks for the advice!

**Comment by wordsworthgroup** [comment]
I installed through miniconda and encountered the same DLL issue
```
ImportError: DLL load failed while importing _stripack: The specified module could not be found.
```
Just FYI. The installation step looked totally normal though
```
Collecting stripy
  Using cached stripy-2.0.2.tar.gz (13.0 MB)
Requirement already satisfied: numpy>=1.16.0 in c:\users\markm\.julia\conda\3\lib\site-packages (from stripy) (1.19.2)
Collecting scipy>=1.0.0
  Downloading scipy-1.6.2-cp38-cp38-win_amd64.whl (32.7 MB)
     |████████████████████████████████| 32.7 MB 6.4 MB/s
Building wheels for collected packages: stripy
  Building wheel for stripy (setup.py) ... done
  Created wheel for stripy: filename=stripy-2.0.2-cp38-cp38-win_amd64.whl size=14698738 sha256=8875506b2393e0a899201d23e1a586de0a2b00fafe5e7b0c152b97856e900788
  Stored in directory: c:\users\markm\appdata\local\pip\cache\wheels\62\ba\84\7c422d85a76077dda43b0cf005ab2bf3f1f89506f7c6e674e1
Successfully built stripy
Installing collected packages: scipy, stripy
Successfully installed scipy-1.6.2 stripy-2.0.2
```

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1617096625/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/e000dd5b474c618c0393301a6aedce7d/e8a6bf7830ae2cc1c11eb269a66cd0df/newton.gif]
I am not totally clear about that installation step.

The conda install should be for the pre-built binaries

     conda install -c geo-down-under stripy

and it should not be showing any of the build steps. We don’t really know if they work on anything other than our test machines, admittedly.

Louis

On Sat, Mar 27, 2021 at 2:11 AM, Wordsworth Group ***@***.***> wrote:

I installed through miniconda and encountered the same DLL issue

ImportError: DLL load failed while importing _stripack: The specified module could not be found.



Just FYI. The installation step looked totally normal though

Collecting stripy

  Using cached stripy-2.0.2.tar.gz (13.0 MB)

Requirement already satisfied: numpy>=1.16.0 in c:\users\markm\.julia\conda\3\lib\site-packages (from stripy) (1.19.2)

Collecting scipy>=1.0.0

  Downloading scipy-1.6.2-cp38-cp38-win_amd64.whl (32.7 MB)

     |████████████████████████████████| 32.7 MB 6.4 MB/s

Building wheels for collected packages: stripy

  Building wheel for stripy (setup.py) ... done

  Created wheel for stripy: filename=stripy-2.0.2-cp38-cp38-win_amd64.whl size=14698738 sha256=8875506b2393e0a899201d23e1a586de0a2b00fafe5e7b0c152b97856e900788

  Stored in directory: c:\users\markm\appdata\local\pip\cache\wheels\62\ba\84\7c422d85a76077dda43b0cf005ab2bf3f1f89506f7c6e674e1

Successfully built stripy

Installing collected packages: scipy, stripy

Successfully installed scipy-1.6.2 stripy-2.0.2
