### ISSUE TITLE
Fortran Routine Compilation Error

### ISSUE THREAD

**Issue by ledragna** [underworldcode/stripy#91]
Hello everyone, 

I encountered an error when installing stripy both from source and with pip.
This is due to a compilation error of the fortran routine. 

**PROBLEM:**
The calls to [intrc0] (l. 7364-7365) and [intrc1] (l. 7391-7392) in srfpack.f are not compliant with the Fortran standard and raise an error with GFortran 10.2.1 (Debian) and (Arch Linux):
lcc is expected as a rank-1 array in the definition of the subroutines, but is passed as a scalar.

**FIX:**
Replace "lcc" in l. 7357 and 7383 with "lcc(1)"

I hope this is useful

Best

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1619048718/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/c135c3d66b7bc69b1847b258792a47be/9efab2399c7c560b34de477b9aa0a465/newton.gif]
If you would like to submit this as a pull request so we have a record of your contribution, feel free to do so. Otherwise we can do it for you but it won’t be recorded in the stripy repo.

Let us know, and thanks for your help !

L

Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Wed, Apr 21, 2021 at 10:58 PM, Marco Fusè ***@***.***> wrote:

Hello everyone,

I encountered an error when installing stripy both from source and with pip.
This is due to a compilation error of the fortran routine.

PROBLEM:
The calls to [intrc0] (l. 7364-7365) and [intrc1] (l. 7391-7392) in srfpack.f are not compliant with the Fortran standard and raise an error with GFortran 10.2.1 (Debian) and (Arch Linux):
lcc is expected as a rank-1 array in the definition of the subroutines, but is passed as a scalar.

FIX:
Replace "lcc" in l. 7357 and 7383 with "lcc(1)"

I hope this is useful

Best

**Comment by ledragna** [comment]
I just created a pull request. 

it's a great project and I'm glad to be useful with my little contribution.

Best,

Marco
